account/urls.py
from django.apps import apps
from django.conf.urls import url
from django.contrib.auth.views import (
    LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from django.core.urlresolvers import reverse_lazy

from .views import (
    UserCreateView, UserCreateDoneTemplateView, UserLoginView, UserActivateView
)

urlpatterns = [
    url(r'^login/$',
        UserLoginView.as_view(), name='login'),
    url(r'^logout/$',
        LogoutView.as_view(), name='logout'),
    url(r'^password_change/$',
        PasswordChangeView.as_view(success_url=reverse_lazy('account:password_change_done')), name='password_change'),
    url(r'^password_change/done/$',
        PasswordChangeDoneView.as_view(), name='password_change_done'),
    url(r'^password_reset/$',
        PasswordResetView.as_view(success_url=reverse_lazy('account:password_reset_done')), name='password_reset'),
    url(r'^password_reset/done/$',
        PasswordResetDoneView.as_view(), name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordResetConfirmView.as_view(success_url=reverse_lazy('account:password_reset_complete')),
        name='password_reset_confirm'),
    url(r'^reset/done/$',
        PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    url(r'^register/$',
        UserCreateView.as_view(), name='register'),
    url(r'^register/done/$',
        UserCreateDoneTemplateView.as_view(), name='register-done'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        UserActivateView.as_view(), name='activate')
]

if apps.is_installed('board'):
    from board.views import MessageChangeListView

    urlpatterns += [
        url(r'^messages/$',
            MessageChangeListView.as_view(), name='account-message-change'),
    ]

conf/urls.py
from django.conf import settings
from django.conf.urls import (
    url, include
)
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from account.views import UserLoginView

urlpatterns = [
    # Index page
    url(r'^$',
        RedirectView.as_view(url='/page/index'), name='index'),

    # Project own apps
    url(r'^blog/',
        include('blog.urls', namespace='blog')),
    url(r'^board/',
        include('board.urls', namespace='board')),
    url(r'^page/',
        include('page.urls', namespace='page')),
    url(r'^accounts/',
        include('account.urls', namespace='account')),

    url(r'^comments/',
        include('django_comments_xtd.urls')),

    # Admin site
    # Redirect default admin login page into custom login page
    url(r'admin/login/',
        UserLoginView.as_view()),
    url(r'^admin/',
        admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load i18n %}
{% load cache %}
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="ko"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Title{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static "images/favicon.ico" %}">
    <link rel="apple-touch-icon" href="{% static "images/apple-touch-icon.png" %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    {% block extrastyle %}{% endblock %}

    <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
</head>
<body>
<!--[if lt IE 8]>
<p class="browserupgrade">
You are using an <strong>outdated</strong> browser.
Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.
</p>
<![endif]-->

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">Rabiang</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {% load navbar_tags %}
            {% cache 600 top_menu %}
                {% navbar_menu 'top_menu' 'menu.html' %}
            {% endcache %}

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_active %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle"
                           data-toggle="dropdown"
                           role="button"
                           aria-haspopup="true"
                           aria-expanded="false">
                            <i class="fa fa-user fa-fw" aria-hidden="true"></i>
                            {{ request.user.nickname|truncatechars:16 }} <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_superuser %}
                                <li>
                                    <a href="{% url 'admin:index' %}">
                                        <i class="fa fa-cog fa-fw" aria-hidden="true"></i>
                                        {% trans 'Admin' %}</a>
                                </li>
                                <li role="separator" class="divider"></li>
                            {% endif %}
                            <li>
                                <a href="{% url 'account:account-message-change' %}">
                                    <i class="fa fa-file-o fa-fw" aria-hidden="true"></i>
                                    {% trans 'My messages' %}
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'account:password_change' %}">
                                    <i class="fa fa-lock fa-fw" aria-hidden="true"></i>
                                    {% trans 'Change password' %}
                                </a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <a href="{% url 'account:logout' %}">
                                    <i class="fa fa-sign-out fa-fw" aria-hidden="true"></i>
                                    {% trans 'Logout' %}
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'account:login' %}?next={{ request.path }}">{% trans 'Sign in' %}</a></li>
                    <li><a href="{% url 'account:register' %}">{% trans 'Sign up' %}</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>

{% block content %}body{% endblock %}

<!-- footer container -->
<footer class="footer">
    <hr/>
    <div>
        <p>pincoin.info © 2012-2017, All Rights Reserved.
            <br/><span>Designed and developed by mairoo</span></p>
        <p><a href="//gitlab.com/mairoo/rabiang" target="_blank">GitLab <i class="fa fa-gitlab" aria-hidden="true"></i> </a>
        </p>
    </div>
</footer> <!-- /footer container -->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script src="{% static "js/main.js" %}"></script>
{% block extrascript %}{% endblock %}

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
    (function (b, o, i, l, e, r) {
        b.GoogleAnalyticsObject = l;
        b[l] || (b[l] =
            function () {
                (b[l].q = b[l].q || []).push(arguments)
            });
        b[l].l = +new Date;
        e = o.createElement(i);
        r = o.getElementsByTagName(i)[0];
        e.src = '//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e, r)
    }(window, document, 'script', 'ga'));
    ga('create', 'UA-XXXXX-X', 'auto');
    ga('send', 'pageview');
</script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Rabiang{% endblock %}

{% block content %}
    <div class="container">
        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron spacer_30">
            <h1>Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout
                called a
                jumbotron and three supporting pieces of content. Use it as a starting point to create something
                more
                unique.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>Latest Features</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Feature Label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More
                            Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Feature Label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More
                            Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Feature Label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More
                            Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <img src="http://placehold.it/800x500" alt="">
                    <div class="caption">
                        <h3>Feature Label</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <p>
                            <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More
                            Info</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                    mauris
                    condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                    mollis
                    euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor
                    mauris
                    condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
                    mollis
                    euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id
                    ligula
                    porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum
                    nibh,
                    ut
                    fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>
        <!-- /.row -->
    </div> <!-- /container -->
{% endblock %}